
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2019-06-19 14:21:11 by lichen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ITS.Model.Mall
{    

    public class MallPaymentRecord
    {
        
        /// <summary>
        /// 主键ID
        /// </summary>        
        public int Id { get; set; }
        
        /// <summary>
        /// 结账信息id
        /// </summary>        
        public int PaymentId { get; set; }
        
        /// <summary>
        /// 金额
        /// </summary>        
        public decimal Cash { get; set; }
        
        /// <summary>
        /// 1：待收/待付，2：延期，3：已收/已付，分期一般是事先约定的，可能需要提前设置，预留状态
        /// </summary>        
        public int Status { get; set; }
        
        /// <summary>
        /// 实际支付时间
        /// </summary>        
        public DateTime CashDate { get; set; }
        
        /// <summary>
        /// 预定支付/收款时间
        /// </summary>        
        public DateTime OriDate { get; set; }
        
        /// <summary>
        /// 备注
        /// </summary>        
        public string Remarks { get; set; }
        
        /// <summary>
        /// 添加时间
        /// </summary>        
        public DateTime CreateTime { get; set; }
         
      
    }
}

